ALTER TABLE zones
  ADD COLUMN IF NOT EXISTS strength INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS source_time TIMESTAMP,
  ADD COLUMN IF NOT EXISTS touched_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS mitigated_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS broken_at TIMESTAMP;
