CREATE TABLE IF NOT EXISTS setup_journal (
  id BIGSERIAL PRIMARY KEY,
  signal_id INTEGER UNIQUE REFERENCES signals(id) ON DELETE SET NULL,
  symbol VARCHAR(32) NOT NULL,
  strategy_name VARCHAR(100) NOT NULL,
  strategy_version VARCHAR(50) NOT NULL,
  timeframe VARCHAR(16) NOT NULL,
  direction VARCHAR(8) NOT NULL CHECK (direction IN ('BUY', 'SELL')),
  setup_stage VARCHAR(32) NOT NULL DEFAULT 'READY',
  quality_score NUMERIC(5,2),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  outcome VARCHAR(32) NOT NULL DEFAULT 'pending',
  d1_bias VARCHAR(32),
  h4_bias VARCHAR(32),
  h1_trend VARCHAR(32),
  ema_confirmation BOOLEAN,
  zone_type VARCHAR(16),
  zone_timeframe VARCHAR(16),
  zone_high NUMERIC(24,10),
  zone_low NUMERIC(24,10),
  zone_status VARCHAR(32),
  distance_from_zone NUMERIC(24,10),
  entry NUMERIC(24,10) NOT NULL,
  stop_loss NUMERIC(24,10) NOT NULL,
  tp1 NUMERIC(24,10) NOT NULL,
  tp2 NUMERIC(24,10),
  risk_reward_tp1 NUMERIC(10,4),
  risk_reward_tp2 NUMERIC(10,4),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  triggered_at TIMESTAMP,
  closed_at TIMESTAMP,
  max_favourable_move NUMERIC(24,10),
  max_adverse_move NUMERIC(24,10),
  final_r_result NUMERIC(12,4),
  review_status VARCHAR(16) NOT NULL DEFAULT 'unreviewed',
  reviewer_notes TEXT,
  screenshot_url TEXT,
  tags TEXT[],
  data_source VARCHAR(64) NOT NULL,
  provider_symbol VARCHAR(64) NOT NULL,
  tradingview_symbol VARCHAR(64) NOT NULL,
  price_scale_mode VARCHAR(32) NOT NULL,
  source_mode VARCHAR(32) NOT NULL,
  CONSTRAINT setup_journal_status_check CHECK (status IN ('pending', 'watching', 'triggered', 'tp1_hit', 'tp2_hit', 'stopped_out', 'invalidated', 'expired', 'manually_closed')),
  CONSTRAINT setup_journal_outcome_check CHECK (outcome IN ('pending', 'watching', 'triggered', 'tp1_hit', 'tp2_hit', 'stopped_out', 'invalidated', 'expired', 'manually_closed')),
  CONSTRAINT setup_journal_review_status_check CHECK (review_status IN ('unreviewed', 'reviewed', 'ignored'))
);

CREATE INDEX IF NOT EXISTS idx_setup_journal_symbol ON setup_journal (symbol);
CREATE INDEX IF NOT EXISTS idx_setup_journal_strategy_name ON setup_journal (strategy_name);
CREATE INDEX IF NOT EXISTS idx_setup_journal_status ON setup_journal (status);
CREATE INDEX IF NOT EXISTS idx_setup_journal_outcome ON setup_journal (outcome);
CREATE INDEX IF NOT EXISTS idx_setup_journal_created_at ON setup_journal (created_at DESC);
